// Centralized icon imports and configuration
import { 
  ShoppingCart, 
  Heart, 
  Star, 
  Trash2, 
  Plus, 
  Minus,
  Home,
  User,
  Search,
  Filter,
  ChevronLeft,
  ChevronRight,
  Package,
  Truck,
  CreditCard,
  LogOut,
  Settings,
  Bell,
  Eye,
  EyeOff,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Edit,
  Save,
  X,
  Check,
  AlertCircle,
  Info,
  Sun,
  Moon
} from 'lucide-react';

import { 
  FaShoppingCart,
  FaHeart,
  FaStar,
  FaTrash,
  FaPlus,
  FaMinus,
  FaHome,
  FaUser,
  FaSearch,
  FaFilter,
  FaChevronLeft,
  FaChevronRight,
  FaBox,
  FaTruck,
  FaCreditCard,
  FaSignOutAlt,
  FaCog,
  FaBell,
  FaEye,
  FaEyeSlash,
  FaChevronDown,
  FaChevronUp,
  FaExternalLinkAlt,
  FaEdit,
  FaSave,
  FaTimes,
  FaCheck,
  FaExclamationCircle,
  FaInfoCircle,
  FaSun,
  FaMoon
} from 'react-icons/fa';

// Icon size constants
export const ICON_SIZES = {
  xs: 12,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
  xxl: 48
};

// Export both lucide and font awesome icons
export const Icons = {
  lucide: {
    shoppingCart: ShoppingCart,
    heart: Heart,
    star: Star,
    trash: Trash2,
    plus: Plus,
    minus: Minus,
    home: Home,
    user: User,
    search: Search,
    filter: Filter,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    package: Package,
    truck: Truck,
    creditCard: CreditCard,
    logOut: LogOut,
    settings: Settings,
    bell: Bell,
    eye: Eye,
    eyeOff: EyeOff,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    externalLink: ExternalLink,
    edit: Edit,
    save: Save,
    close: X,
    check: Check,
    alert: AlertCircle,
    info: Info,
    sun: Sun,
    moon: Moon
  },
  fa: {
    shoppingCart: FaShoppingCart,
    heart: FaHeart,
    star: FaStar,
    trash: FaTrash,
    plus: FaPlus,
    minus: FaMinus,
    home: FaHome,
    user: FaUser,
    search: FaSearch,
    filter: FaFilter,
    chevronLeft: FaChevronLeft,
    chevronRight: FaChevronRight,
    package: FaBox,
    truck: FaTruck,
    creditCard: FaCreditCard,
    logOut: FaSignOutAlt,
    settings: FaCog,
    bell: FaBell,
    eye: FaEye,
    eyeOff: FaEyeSlash,
    chevronDown: FaChevronDown,
    chevronUp: FaChevronUp,
    externalLink: FaExternalLinkAlt,
    edit: FaEdit,
    save: FaSave,
    close: FaTimes,
    check: FaCheck,
    alert: FaExclamationCircle,
    info: FaInfoCircle,
    sun: FaSun,
    moon: FaMoon
  }
};

// Helper function to get icon by name
export const getIcon = (iconName: string, library: 'lucide' | 'fa' = 'lucide') => {
  return Icons[library][iconName as keyof typeof Icons[typeof library]] || null;
};
